<a href="https://colab.research.google.com/github/AkhileshPatne/home-energy-analyzer/blob/main/Day2_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df = pd.read_excel("Appliences.xlsx")
df.head()

     Appliences  Watts  Hours Per Day
0    Tubelights     90              5
1          LEDs     10              4
2          Fans     50             16
3            AC   1600              3
4  Refrigerator   1500              6

In [2]:
df.shape

(8, 3)

In [3]:
df.columns

Index(['Appliences', 'Watts', 'Hours Per Day'], dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Appliences     8 non-null      object
 1   Watts          8 non-null      int64
 2   Hours Per Day  8 non-null      int64
dtypes: int64(2), object(1)
memory usage: 324.0+ bytes

In [10]:

df.describe()

             Watts  Hours Per Day
count     8.000000       8.000000
mean    831.250000       5.500000
std     783.115345       4.407785
min      10.000000       2.000000
25%      80.000000       3.750000
50%     700.000000       4.000000
75%    1525.000000       5.250000
max    2000.000000      16.000000

In [12]:
df["Watts"]

0      90
1      10
2      50
3    1600
4    1500
5     800
6     600
7    2000
Name: Watts, dtype: int64

In [13]:
df["Watts"].max()

2000

In [14]:
df[df["Watts"]>500]

        Appliences  Watts  Hours Per Day
3               AC   1600              3
4     Refrigerator   1500              6
5      Washmachine    800              2
6               TV    600              4
7  Induction Stove   2000              4

In [15]:
df.sort_values("Hours Per Day",ascending=False)

        Appliences  Watts  Hours Per Day
2             Fans     50             16
4     Refrigerator   1500              6
0       Tubelights     90              5
1             LEDs     10              4
7  Induction Stove   2000              4
6               TV    600              4
3               AC   1600              3
5      Washmachine    800              2

In [21]:
df.sort_values("Watts",ascending=False)

        Appliences  Watts  Hours Per Day
7  Induction Stove   2000              4
3               AC   1600              3
4     Refrigerator   1500              6
5      Washmachine    800              2
6               TV    600              4
0       Tubelights     90              5
2             Fans     50             16
1             LEDs     10              4