<a href="https://colab.research.google.com/github/AkhileshPatne/home-energy-analyzer/blob/main/Day3_Energy_Cal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
df = pd.read_excel("Appliences.xlsx")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Appliences     8 non-null      object
 1   Watts          8 non-null      int64
 2   Hours Per Day  8 non-null      int64
dtypes: int64(2), object(1)
memory usage: 324.0+ bytes

calculating daily kwh for all appliences

In [9]:
df["daily_kwh"] = (df["Watts"]*df["Hours Per Day"])/1000

converting wh to kwh

In [15]:
(df["Watts"] * df["Hours Per Day"])/1000

0    0.45
1    0.04
2    0.80
3    4.80
4    9.00
5    1.60
6    2.40
7    8.00
dtype: float64

# Round the numbers
it keeps decimal to 2 digit so output look clean

In [16]:
df["daily_kwh"] = df["daily_kwh"].round(2)

In [17]:
df["daily_kwh"].round(2)

0    0.45
1    0.04
2    0.80
3    4.80
4    9.00
5    1.60
6    2.40
7    8.00
Name: daily_kwh, dtype: float64

To find the total and biggest consumer,
Total daily energy for household

In [21]:
total_daily = df["daily_kwh"].sum()
print("Total Daily Energy:",round(total_daily,2),"kwh")

Total Daily Energy: 27.09 kwh

for the appliences who use most of the energy

In [23]:
df.sort_values("daily_kwh",ascending=False)

        Appliences  Watts  Hours Per Day  daily_kwh
4     Refrigerator   1500              6       9.00
7  Induction Stove   2000              4       8.00
3               AC   1600              3       4.80
6               TV    600              4       2.40
5      Washmachine    800              2       1.60
2             Fans     50             16       0.80
0       Tubelights     90              5       0.45
1             LEDs     10              4       0.04

Top 3 consumers

In [24]:
df.sort_values("daily_kwh",ascending=False).head(3)

        Appliences  Watts  Hours Per Day  daily_kwh
4     Refrigerator   1500              6        9.0
7  Induction Stove   2000              4        8.0
3               AC   1600              3        4.8

Calculate each applience share of the total

In [28]:
df["percent_of_total"]=(df["daily_kwh"] / total_daily * 100).round(1)
df.sort_values("percent_of_total",ascending=False)

        Appliences  Watts  Hours Per Day  daily_kwh  percent_of_total
4     Refrigerator   1500              6       9.00              33.2
7  Induction Stove   2000              4       8.00              29.5
3               AC   1600              3       4.80              17.7
6               TV    600              4       2.40               8.9
5      Washmachine    800              2       1.60               5.9
2             Fans     50             16       0.80               3.0
0       Tubelights     90              5       0.45               1.7
1             LEDs     10              4       0.04               0.1

the percentage should add upto 100

In [29]:
df["percent_of_total"].sum()

np.float64(100.0)



1.   ***The total daily consumption is 27.09 kwh.***
2.   ***The biggest consumer is Refrigerator using 9.0 kwh.***
3.   ***The highest wattege applience is Induction stove but it still ranks in second.***